# Generated by Django 5.1.6 on 2025-03-18 05:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0002_homeworkhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqami quyidagi formatda bo‘lishi kerak: '9989012345678'. Maksimal 14 ta raqam.", regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
